pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = 'https://jitpack.io' }
        maven {
            url = "https://artifacts.codegenomeproject.org/maven"
            credentials {
                username = providers.environmentVariable("codeGenomeUsername").get()
                password = providers.environmentVariable("codeGenomeToken").get()
            }
        }
    }
}

plugins {
    id 'com.autonomousapps.build-health' version '3.19.1'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = 'https://jitpack.io' }
    }
}

rootProject.name = 'SimpleApp'
include 'hello'
