plugins {
    id 'java-library'
    id 'application'
}

dependencies {
    implementation libs.jfugue
    implementation libs.commons.math3

    compileOnly libs.jspecify

    testImplementation(platform(libs.junit))
    testImplementation libs.bundles.test.implementation
    testCompileOnly libs.jspecify
    testCompileOnly libs.bundles.test.compile
    testRuntimeOnly libs.bundles.test.runtime
}

application {
    mainModule = 'com.ak.app'
    mainClass = 'com.ak.app.MainApp'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}