plugins {
    id 'java-library'
    id 'application'
    alias(libs.plugins.openrewrite)
}

dependencies {
    compileOnly libs.jspecify
    implementation libs.slf4j
    runtimeOnly libs.logback

    testImplementation(platform(libs.junit))
    testImplementation libs.bundles.test.implementation
    testCompileOnly libs.jspecify
    testCompileOnly libs.bundles.test.compile
    testRuntimeOnly libs.bundles.test.runtime

    rewrite libs.rewrite.testing.frameworks
}

application {
    mainModule = 'com.ak.app'
    mainClass = 'com.ak.app.MainApp'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
    maven { url = 'https://jitpack.io' }
    maven { url = 'https://artifacts.codegenomeproject.org/maven' }
}

rewrite {
    activeRecipe('org.openrewrite.java.testing.assertj.JUnitToAssertj')
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}