name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 18
      - name: Set current date as env variable
        run: echo "RELEASE_DATE=$(date +%s)" >> $GITHUB_ENV
      - name: Echo current date
        run: echo ${{ env.RELEASE_DATE }}