name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: $(date +%s)
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 18
      - name: Execute Gradle build
        run: gradle build
      - name: Login to Docker Hub
        run: docker login -u a002k -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Set current date as env variable
        run: echo $TAG_NAME